// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWFoIvG4dbeNOKUm_vmcPhncRaMpkocHs',
    appId: '1:61435977942:web:ace812b65e37e47e71e977',
    messagingSenderId: '61435977942',
    projectId: 'konyasehir9lar-1',
    authDomain: 'konyasehir9lar-1.firebaseapp.com',
    storageBucket: 'konyasehir9lar-1.appspot.com',
    measurementId: 'G-FY4NY1E3X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCexEIyH3h1FDfwRKVkRE3__7cZnDPd-ls',
    appId: '1:61435977942:android:832156e204a38b5671e977',
    messagingSenderId: '61435977942',
    projectId: 'konyasehir9lar-1',
    storageBucket: 'konyasehir9lar-1.appspot.com',
  );
}
